apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: yeo
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: "mongo:4.0"
        name: mongo
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-data-dir
          mountPath: /data/db
      volumes:
      - name: mongodb-data-dir
        hostPath:
          path: /opt/k8s/data/mongodb
          type: Directory
