apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: "mysql:5.7"
        name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data-dir
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data-dir
        hostPath:
          path: /opt/k8s/data/mysql
          type: Directory
